accounts:
  - name: alice
    coins: ["100000000000000000000adelite"]
  - name: bob
    coins: ["5000000000000adelite"]
validator:
  name: alice
  staked: "100000000000000000000adelite"
faucet:
  name: bob 
  coins: ["10adelite"]
build:
  binary: "delited"
init:
  home: "$HOME/.delited"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "delited_28-1"
  app_state:
    staking:
      params:
        bond_denom: "adelite"
    mint:
      params:
        mint_denom: "adelite"
    crisis:
      constant_fee:
        denom: "adelite"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "adelite"
    evm:
      params:
        evm_denom: "adelite"
